#
# RedHat VLAN configuration file
#

- name: Create the VLAN configuration file
  template: src=el_vlan.j2 dest="{{ el_network_sysconfig }}/ifcfg-{{ item.0 }}.{{ item.1 }}" backup=yes
  with_nested:
  - "{{ parents }}"
  - "{{ vlans }}"
  when:
  - apply
  tags:
  - vlan
  - el

- name: Create the VLAN configuration file
  template: src=el_vlan.j2 dest="{{ tmp_dir }}/ifcfg-{{ item.0 }}.{{ item.1 }}"
  with_nested:
  - "{{ parents }}"
  - "{{ vlans }}"
  when:
  - not apply
  tags:
  - vlan
  - el
